# Use container-based infrastructure
sudo: false
language: scala
services:
  - postgresql
jdk:
  - oraclejdk8
scala:
  - 2.11.8
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
script:
  - sbt test
